# 日期： 2018年4月14日
# 软件名： 店面记录 1.0

# -*- coding: utf-8 -*-

from PyQt5 import QtGui, QtWidgets
from PyQt5.QtCore import QDate, QRect, QCoreApplication, Qt, QMetaObject

class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(581, 493)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.section = QtWidgets.QTabWidget(self.centralWidget)
        self.section.setGeometry(QRect(10, 10, 561, 431))
        self.section.setObjectName("section")
        self.debt = QtWidgets.QWidget()
        self.debt.setObjectName("debt")
        self.debt_add_widget = QtWidgets.QWidget(self.debt)
        self.debt_add_widget.setGeometry(QRect(10, 10, 531, 171))
        self.debt_add_widget.setObjectName("debt_add_widget")
        self.debt_add_name_label = QtWidgets.QLabel(self.debt_add_widget)
        self.debt_add_name_label.setGeometry(QRect(10, 10, 31, 21))
        self.debt_add_name_label.setObjectName("debt_add_name_label")
        self.debt_add_number_label = QtWidgets.QLabel(self.debt_add_widget)
        self.debt_add_number_label.setGeometry(QRect(10, 40, 47, 16))
        self.debt_add_number_label.setObjectName("debt_add_number_label")
        self.debt_add_name_input = QtWidgets.QLineEdit(self.debt_add_widget)
        self.debt_add_name_input.setGeometry(QRect(40, 10, 121, 20))
        self.debt_add_name_input.setObjectName("debt_add_name_input")
        self.debt_add_number_input = QtWidgets.QLineEdit(self.debt_add_widget)
        self.debt_add_number_input.setGeometry(QRect(60, 40, 101, 20))
        self.debt_add_number_input.setObjectName("debt_add_number_input")
        self.debt_add_number_input.setValidator(QtGui.QIntValidator())
        self.debt_add_quantity_label = QtWidgets.QLabel(self.debt_add_widget)
        self.debt_add_quantity_label.setGeometry(QRect(190, 10, 47, 21))
        self.debt_add_quantity_label.setObjectName("debt_add_quantity_label")
        self.debt_add_thing_label = QtWidgets.QLabel(self.debt_add_widget)
        self.debt_add_thing_label.setGeometry(QRect(190, 40, 47, 16))
        self.debt_add_thing_label.setObjectName("debt_add_thing_label")
        self.debt_add_euro_label = QtWidgets.QLabel(self.debt_add_widget)
        self.debt_add_euro_label.setGeometry(QRect(316, 10, 16, 20))
        self.debt_add_euro_label.setObjectName("debt_add_euro_label")
        self.debt_add_quantity_input = QtWidgets.QDoubleSpinBox(self.debt_add_widget)
        self.debt_add_quantity_input.setGeometry(QRect(220, 10, 91, 22))
        self.debt_add_quantity_input.setObjectName("debt_add_quantity_input")
        self.debt_add_quantity_input.setMaximum(1000000)
        self.debt_add_thing_input = QtWidgets.QLineEdit(self.debt_add_widget)
        self.debt_add_thing_input.setEnabled(True)
        self.debt_add_thing_input.setGeometry(QRect(220, 40, 299, 20))
        self.debt_add_thing_input.setObjectName("debt_add_thing_input")
        self.debt_add_search_button = QtWidgets.QPushButton(self.debt_add_widget)
        self.debt_add_search_button.setGeometry(QRect(340, 10, 75, 23))
        self.debt_add_search_button.setObjectName("debt_add_search_button")
        self.debt_add_add_button = QtWidgets.QPushButton(self.debt_add_widget)
        self.debt_add_add_button.setGeometry(QRect(430, 10, 75, 23))
        self.debt_add_add_button.setObjectName("debt_add_add_button")
        self.debt_add_table = QtWidgets.QTableWidget(self.debt_add_widget)
        self.debt_add_table.setGeometry(QRect(10, 70, 511, 91))
        self.debt_add_table.setAutoFillBackground(False)
        self.debt_add_table.setAutoScroll(True)
        self.debt_add_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers) # deshabilita
        self.debt_add_table.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.debt_add_table.setObjectName("debt_add_table")
        self.debt_add_table.setColumnCount(3)
        self.debt_add_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.debt_add_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_add_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_add_table.setHorizontalHeaderItem(2, item)
        self.debt_add_table.setColumnWidth(2, 200)
        self.debt_search_widget = QtWidgets.QWidget(self.debt)
        self.debt_search_widget.setGeometry(QRect(10, 190, 531, 211))
        self.debt_search_widget.setObjectName("debt_search_widget")
        self.debt_search_begin_label = QtWidgets.QLabel(self.debt_search_widget)
        self.debt_search_begin_label.setGeometry(QRect(10, 10, 16, 21))
        self.debt_search_begin_label.setObjectName("debt_search_begin_label")
        self.debt_search_end_label = QtWidgets.QLabel(self.debt_search_widget)
        self.debt_search_end_label.setGeometry(QRect(10, 40, 16, 20))
        self.debt_search_end_label.setObjectName("debt_search_end_label")
        self.debt_search_begin_date = QtWidgets.QDateEdit(self.debt_search_widget)
        self.debt_search_begin_date.setGeometry(QRect(30, 10, 111, 22))
        self.debt_search_begin_date.setDate(QDate(QDate(2017, 1, 1)))
        self.debt_search_begin_date.setMinimumDate(QDate(QDate(2017, 1, 1)))
        self.debt_search_begin_date.setMaximumDate(QDate.currentDate())
        self.debt_search_begin_date.setCurrentSection(QtWidgets.QDateEdit.DaySection)
        self.debt_search_begin_date.setCalendarPopup(True)
        self.debt_search_begin_date.setObjectName("debt_search_begin_date")
        self.debt_search_end_date = QtWidgets.QDateEdit(self.debt_search_widget)
        self.debt_search_end_date.setGeometry(QRect(30, 40, 111, 22))
        self.debt_search_end_date.setDate(QDate.currentDate())
        self.debt_search_end_date.setMinimumDate(QDate(QDate(2017, 1, 1)))
        self.debt_search_end_date.setMaximumDate(QDate.currentDate())
        self.debt_search_end_date.setCalendarPopup(True)
        self.debt_search_end_date.setObjectName("debt_search_end_date")
        self.debt_search_name_label = QtWidgets.QLabel(self.debt_search_widget)
        self.debt_search_name_label.setGeometry(QRect(170, 10, 31, 21))
        self.debt_search_name_label.setObjectName("debt_search_name_label")
        self.debt_search_name_input = QtWidgets.QLineEdit(self.debt_search_widget)
        self.debt_search_name_input.setGeometry(QRect(210, 10, 121, 20))
        self.debt_search_name_input.setObjectName("debt_search_name_input")
        self.debt_search_search_button = QtWidgets.QPushButton(self.debt_search_widget)
        self.debt_search_search_button.setGeometry(QRect(440, 40, 81, 23))
        self.debt_search_search_button.setObjectName("debt_search_search_button")
        self.debt_search_delete_button = QtWidgets.QPushButton(self.debt_search_widget)
        self.debt_search_delete_button.setGeometry(QRect(440, 190, 81, 22))
        self.debt_search_delete_button.setObjectName("debt_search_delete_button")
        self.debt_search_table = QtWidgets.QTableWidget(self.debt_search_widget)
        self.debt_search_table.setGeometry(QRect(10, 70, 511, 121))
        self.debt_search_table.setColumnCount(5)
        self.debt_search_table.setObjectName("debt_search_table")
        self.debt_search_table.setRowCount(0)
        self.debt_search_table.setSelectionBehavior(QtWidgets.QTableView.SelectRows) # solo seleciona por fila
        self.debt_search_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers) # deshabilita la edición
        item = QtWidgets.QTableWidgetItem()
        self.debt_search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_search_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.debt_search_table.setHorizontalHeaderItem(4, item)
        self.debt_search_table.setColumnWidth(4, 300)
        self.debt_search_number_label = QtWidgets.QLabel(self.debt_search_widget)
        self.debt_search_number_label.setGeometry(QRect(350, 10, 47, 21))
        self.debt_search_number_label.setObjectName("debt_search_number_label")
        self.debt_search_number_input = QtWidgets.QLineEdit(self.debt_search_widget)
        self.debt_search_number_input.setGeometry(QRect(410, 10, 111, 20))
        self.debt_search_number_input.setObjectName("debt_search_number_input")
        self.debt_search_number_input.setValidator(QtGui.QIntValidator())
        self.debt_search_description_label = QtWidgets.QLabel(self.debt_search_widget)
        self.debt_search_description_label.setGeometry(QRect(170, 40, 47, 16))
        self.debt_search_description_label.setObjectName("debt_search_description_label")
        self.debt_search_description_input = QtWidgets.QLineEdit(self.debt_search_widget)
        self.debt_search_description_input.setGeometry(QRect(220, 40, 191, 20))
        self.debt_search_description_input.setObjectName("debt_search_description_input")
        self.debt_label1 = QtWidgets.QLabel(self.debt)
        self.debt_label1.setGeometry(QRect(26, 0, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.debt_label1.setFont(font)
        self.debt_label1.setObjectName("debt_label1")
        self.debt_label2 = QtWidgets.QLabel(self.debt)
        self.debt_label2.setGeometry(QRect(20, 180, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.debt_label2.setFont(font)
        self.debt_label2.setObjectName("debt_label2")
        self.section.addTab(self.debt, "")
        self.check_in = QtWidgets.QWidget()
        self.check_in.setObjectName("check_in")
        self.check_in_add_widget = QtWidgets.QWidget(self.check_in)
        self.check_in_add_widget.setGeometry(QRect(10, 10, 531, 61))
        self.check_in_add_widget.setObjectName("check_in_add_widget")
        self.check_in_add_date_label = QtWidgets.QLabel(self.check_in_add_widget)
        self.check_in_add_date_label.setGeometry(QRect(20, 20, 21, 21))
        self.check_in_add_date_label.setObjectName("check_in_add_date_label")
        self.check_in_add_date = QtWidgets.QDateEdit(self.check_in_add_widget)
        self.check_in_add_date.setGeometry(QRect(50, 20, 110, 21))
        self.check_in_add_date.setObjectName("check_in_add_date")
        self.check_in_add_date.setDate(QDate.currentDate())
        self.check_in_add_date.setMinimumDate(QDate(2017, 1, 1))
        self.check_in_add_date.setMaximumDate(QDate.currentDate())
        self.check_in_add_date.setCalendarPopup(True)
        self.check_in_add_quantity_label = QtWidgets.QLabel(self.check_in_add_widget)
        self.check_in_add_quantity_label.setGeometry(QRect(190, 20, 21, 21))
        self.check_in_add_quantity_label.setObjectName("check_in_add_quantity_label")
        self.check_in_add_euro_label = QtWidgets.QLabel(self.check_in_add_widget)
        self.check_in_add_euro_label.setGeometry(QRect(330, 20, 21, 16))
        self.check_in_add_euro_label.setObjectName("check_in_add_euro_label")
        self.check_in_add_add_button = QtWidgets.QPushButton(self.check_in_add_widget)
        self.check_in_add_add_button.setGeometry(QRect(370, 20, 75, 23))
        self.check_in_add_add_button.setObjectName("check_in_add_add_button")
        self.check_in_add_quantity = QtWidgets.QDoubleSpinBox(self.check_in_add_widget)
        self.check_in_add_quantity.setGeometry(QRect(220, 20, 101, 22))
        self.check_in_add_quantity.setObjectName("check_in_add_quantity")
        self.check_in_add_quantity.setMaximum(10000000)
        self.check_in_label1 = QtWidgets.QLabel(self.check_in)
        self.check_in_label1.setGeometry(QRect(30, 0, 47, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_in_label1.setFont(font)
        self.check_in_label1.setObjectName("check_in_label1")
        self.check_in_label2 = QtWidgets.QLabel(self.check_in)
        self.check_in_label2.setGeometry(QRect(30, 90, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_in_label2.setFont(font)
        self.check_in_label2.setObjectName("check_in_label2")
        self.check_in_search_widget = QtWidgets.QWidget(self.check_in)
        self.check_in_search_widget.setGeometry(QRect(9, 109, 531, 281))
        self.check_in_search_widget.setObjectName("check_in_search_widget")
        self.check_in_search_end_date = QtWidgets.QDateEdit(self.check_in_search_widget)
        self.check_in_search_end_date.setGeometry(QRect(220, 10, 111, 22))
        self.check_in_search_end_date.setDate(QDate(QDate.currentDate()))
        self.check_in_search_end_date.setMinimumDate(QDate(QDate(2017, 1, 1)))
        self.check_in_search_end_date.setMaximumDate(QDate(QDate.currentDate()))
        self.check_in_search_end_date.setCalendarPopup(True)
        self.check_in_search_end_date.setObjectName("check_in_search_end_date")
        self.check_in_search_end_label = QtWidgets.QLabel(self.check_in_search_widget)
        self.check_in_search_end_label.setGeometry(QRect(190, 10, 16, 20))
        self.check_in_search_end_label.setObjectName("check_in_search_end_label")
        self.check_in_search_begin_date = QtWidgets.QDateEdit(self.check_in_search_widget)
        self.check_in_search_begin_date.setGeometry(QRect(50, 10, 111, 22))
        self.check_in_search_begin_date.setDate(QDate(QDate(2017, 1, 1)))
        self.check_in_search_begin_date.setMinimumDate(QDate(QDate(2017, 1, 1)))
        self.check_in_search_begin_date.setMaximumDate(QDate.currentDate())
        self.check_in_search_begin_date.setCurrentSection(QtWidgets.QDateEdit.DaySection)
        self.check_in_search_begin_date.setCalendarPopup(True)
        self.check_in_search_begin_date.setObjectName("check_in_search_begin_date")
        self.check_in_search_search_button = QtWidgets.QPushButton(self.check_in_search_widget)
        self.check_in_search_search_button.setGeometry(QRect(370, 10, 81, 23))
        self.check_in_search_search_button.setObjectName("check_in_search_search_button")
        self.check_in_search_begin_label = QtWidgets.QLabel(self.check_in_search_widget)
        self.check_in_search_begin_label.setGeometry(QRect(20, 10, 16, 21))
        self.check_in_search_begin_label.setObjectName("check_in_search_begin_label")
        self.check_in_search_table = QtWidgets.QTableWidget(self.check_in_search_widget)
        self.check_in_search_table.setGeometry(QRect(10, 50, 521, 191))
        self.check_in_search_table.setObjectName("check_in_search_table")
        self.check_in_search_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers) # deshabilitar
        self.check_in_search_table.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.check_in_search_table.setColumnCount(2)
        self.check_in_search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.check_in_search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.check_in_search_table.setHorizontalHeaderItem(1, item)
        self.check_in_search_table.setColumnWidth(0, 175)
        self.check_in_search_table.setColumnWidth(1, 175)
        self.check_in_search_total_label = QtWidgets.QLabel(self.check_in_search_widget)
        self.check_in_search_total_label.setGeometry(QRect(210, 250, 31, 16))
        self.check_in_search_total_label.setObjectName("check_in_search_total_label")
        self.check_in_search_total_input = QtWidgets.QLineEdit(self.check_in_search_widget)
        self.check_in_search_total_input.setEnabled(False)
        self.check_in_search_total_input.setGeometry(QRect(240, 250, 113, 20))
        self.check_in_search_total_input.setObjectName("check_in_search_total_input")
        self.section.addTab(self.check_in, "")
        self.person = QtWidgets.QWidget()
        self.person.setObjectName("person")
        self.person_add_widget = QtWidgets.QWidget(self.person)
        self.person_add_widget.setGeometry(QRect(10, 20, 531, 71))
        self.person_add_widget.setObjectName("person_add_widget")
        self.person_add_name_label = QtWidgets.QLabel(self.person_add_widget)
        self.person_add_name_label.setGeometry(QRect(20, 10, 31, 16))
        self.person_add_name_label.setObjectName("person_add_name_label")
        self.person_add_description_label = QtWidgets.QLabel(self.person_add_widget)
        self.person_add_description_label.setGeometry(QRect(10, 40, 47, 21))
        self.person_add_description_label.setObjectName("person_add_description_label")
        self.person_add_name_input = QtWidgets.QLineEdit(self.person_add_widget)
        self.person_add_name_input.setGeometry(QRect(60, 10, 113, 20))
        self.person_add_name_input.setObjectName("person_add_name_input")
        self.person_add_description_input = QtWidgets.QLineEdit(self.person_add_widget)
        self.person_add_description_input.setGeometry(QRect(60, 40, 341, 20))
        self.person_add_description_input.setObjectName("person_add_description_input")
        self.person_add_add_button = QtWidgets.QPushButton(self.person_add_widget)
        self.person_add_add_button.setGeometry(QRect(430, 40, 75, 23))
        self.person_add_add_button.setObjectName("person_add_add_button")
        self.person_search_widget = QtWidgets.QWidget(self.person)
        self.person_search_widget.setGeometry(QRect(10, 110, 531, 281))
        self.person_search_widget.setObjectName("person_search_widget")
        self.person_search_name_label = QtWidgets.QLabel(self.person_search_widget)
        self.person_search_name_label.setGeometry(QRect(10, 10, 31, 21))
        self.person_search_name_label.setObjectName("person_search_name_label")
        self.person_search_number_label = QtWidgets.QLabel(self.person_search_widget)
        self.person_search_number_label.setGeometry(QRect(230, 10, 47, 16))
        self.person_search_number_label.setObjectName("person_search_number_label")
        self.person_search_name_input = QtWidgets.QLineEdit(self.person_search_widget)
        self.person_search_name_input.setGeometry(QRect(40, 10, 171, 20))
        self.person_search_name_input.setObjectName("person_search_name_input")
        self.person_search_number_input = QtWidgets.QLineEdit(self.person_search_widget)
        self.person_search_number_input.setGeometry(QRect(290, 10, 121, 20))
        self.person_search_number_input.setObjectName("person_search_number_input")
        self.person_search_number_input.setValidator(QtGui.QIntValidator())
        self.person_search_table = QtWidgets.QTableWidget(self.person_search_widget)
        self.person_search_table.setGeometry(QRect(10, 70, 511, 201))
        self.person_search_table.setAutoFillBackground(False)
        self.person_search_table.setAutoScroll(True)
        self.person_search_table.setObjectName("person_search_table")
        self.person_search_table.setColumnCount(4)
        self.person_search_table.setRowCount(0)
        self.person_search_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers) # deshabilita
        self.person_search_table.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        item = QtWidgets.QTableWidgetItem(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.person_search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.person_search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.person_search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.person_search_table.setHorizontalHeaderItem(3, item)
        self.person_search_search_button = QtWidgets.QPushButton(self.person_search_widget)
        self.person_search_search_button.setGeometry(QRect(430, 40, 75, 23))
        self.person_search_search_button.setObjectName("person_search_search_button")
        self.person_search_description_label = QtWidgets.QLabel(self.person_search_widget)
        self.person_search_description_label.setGeometry(QRect(10, 40, 47, 21))
        self.person_search_description_label.setObjectName("person_search_description_label")
        self.person_search_description_input = QtWidgets.QLineEdit(self.person_search_widget)
        self.person_search_description_input.setGeometry(QRect(70, 40, 341, 20))
        self.person_search_description_input.setObjectName("person_search_description_input")
        self.person_label1 = QtWidgets.QLabel(self.person)
        self.person_label1.setGeometry(QRect(20, 10, 47, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.person_label1.setFont(font)
        self.person_label1.setObjectName("person_label1")
        self.person_label2 = QtWidgets.QLabel(self.person)
        self.person_label2.setGeometry(QRect(20, 100, 47, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.person_label2.setFont(font)
        self.person_label2.setObjectName("person_label2")
        self.section.addTab(self.person, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QRect(0, 0, 581, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.setWindowFlags(self.windowFlags() | Qt.WindowMinimizeButtonHint)
        self.retranslateUi(MainWindow)
        self.section.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "店面记录 1.0"))
        if self.language == "ch":
            self.debt_add_name_label.setText(_translate("MainWindow", "名字"))
            self.debt_add_number_label.setText(_translate("MainWindow", "人物编号"))
            self.debt_add_quantity_label.setText(_translate("MainWindow", "数目"))
            self.debt_add_thing_label.setText(_translate("MainWindow", "物品"))
            self.debt_add_euro_label.setText(_translate("MainWindow", "€"))
            item = self.debt_add_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "人物编号"))
            item = self.debt_add_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "名字"))
            item = self.debt_add_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "人物介绍"))
            self.debt_add_add_button.setText(_translate("MainWindow", "添加"))
            self.debt_add_search_button.setText(_translate("MainWindow", "查找人物"))
            self.debt_search_begin_label.setText(_translate("MainWindow", "从"))
            self.debt_search_end_label.setText(_translate("MainWindow", "到"))
            self.debt_search_name_label.setText(_translate("MainWindow", "名字"))
            self.debt_search_search_button.setText(_translate("MainWindow", "查找"))
            self.debt_search_delete_button.setText(_translate("MainWindow", "删除"))
            item = self.debt_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "人物编号"))
            item = self.debt_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "名字"))
            item = self.debt_search_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "日期"))
            item = self.debt_search_table.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "数目"))
            item = self.debt_search_table.horizontalHeaderItem(4)
            item.setText(_translate("MainWindow", "物品"))
            self.debt_search_number_label.setText(_translate("MainWindow", "人物编号"))
            self.debt_search_description_label.setText(_translate("MainWindow", "人物介绍"))
            self.debt_label1.setText(_translate("MainWindow", "添加"))
            self.debt_label2.setText(_translate("MainWindow", "查找"))
            self.section.setTabText(self.section.indexOf(self.debt), _translate("MainWindow", "欠款"))
            self.check_in_add_date_label.setText(_translate("MainWindow", "日期"))
            self.check_in_add_quantity_label.setText(_translate("MainWindow", "数目"))
            self.check_in_add_euro_label.setText(_translate("MainWindow", "€"))
            self.check_in_add_add_button.setText(_translate("MainWindow", "添加"))
            self.check_in_label1.setText(_translate("MainWindow", "添加"))
            self.check_in_label2.setText(_translate("MainWindow", "查找"))
            self.check_in_search_end_label.setText(_translate("MainWindow", "到"))
            self.check_in_search_search_button.setText(_translate("MainWindow", "查找"))
            self.check_in_search_begin_label.setText(_translate("MainWindow", "从"))
            item = self.check_in_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "日期"))
            item = self.check_in_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "数目"))
            self.check_in_search_total_label.setText(_translate("MainWindow", "总计:"))
            self.section.setTabText(self.section.indexOf(self.check_in), _translate("MainWindow", "账单"))
            self.person_add_name_label.setText(_translate("MainWindow", "名字"))
            self.person_add_description_label.setText(_translate("MainWindow", "人物介绍"))
            self.person_add_add_button.setText(_translate("MainWindow", "添加"))
            self.person_search_name_label.setText(_translate("MainWindow", "名字"))
            self.person_search_number_label.setText(_translate("MainWindow", "人物编号"))
            item = self.person_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "人物编号"))
            item = self.person_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "名字"))
            item = self.person_search_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "总欠款"))
            item = self.person_search_table.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "人物介绍"))
            self.person_search_table.setColumnWidth(3, 190)
            self.person_search_search_button.setText(_translate("MainWindow", "查找人物"))
            self.person_search_description_label.setText(_translate("MainWindow", "人物介绍"))
            self.person_label1.setText(_translate("MainWindow", "添加人物"))
            self.person_label2.setText(_translate("MainWindow", "查找人物"))
            self.section.setTabText(self.section.indexOf(self.person), _translate("MainWindow", "人物"))
        else:
            self.debt_add_name_label.setText(_translate("MainWindow", "Nombre"))
            self.debt_add_number_label.setText(_translate("MainWindow", "ID"))
            self.debt_add_quantity_label.setText(_translate("MainWindow", "Cuantía"))
            self.debt_add_thing_label.setText(_translate("MainWindow", "Productos"))
            self.debt_add_euro_label.setText(_translate("MainWindow", "€"))
            item = self.debt_add_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "ID"))
            item = self.debt_add_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "Nombre"))
            item = self.debt_add_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "Descripción"))
            self.debt_add_add_button.setText(_translate("MainWindow", "Crear"))
            self.debt_add_search_button.setText(_translate("MainWindow", "Buscar"))
            self.debt_search_begin_label.setText(_translate("MainWindow", "Desde"))
            self.debt_search_end_label.setText(_translate("MainWindow", "Hasta"))
            self.debt_search_name_label.setText(_translate("MainWindow", "Nombre"))
            self.debt_search_search_button.setText(_translate("MainWindow", "Buscar"))
            self.debt_search_delete_button.setText(_translate("MainWindow", "Cobrado"))
            item = self.debt_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "ID"))
            item = self.debt_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "Nombre"))
            item = self.debt_search_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "Fecha"))
            item = self.debt_search_table.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "Cuantía"))
            item = self.debt_search_table.horizontalHeaderItem(4)
            item.setText(_translate("MainWindow", "Productos"))
            self.debt_search_number_label.setText(_translate("MainWindow", "ID"))
            self.debt_search_description_label.setText(_translate("MainWindow", "Descripción"))
            self.debt_label1.setText(_translate("MainWindow", "Crear"))
            self.debt_label2.setText(_translate("MainWindow", "Buscar"))
            self.section.setTabText(self.section.indexOf(self.debt), _translate("MainWindow", "Deuda"))
            self.check_in_add_date_label.setText(_translate("MainWindow", "Fecha"))
            self.check_in_add_quantity_label.setText(_translate("MainWindow", "Cuantía"))
            self.check_in_add_euro_label.setText(_translate("MainWindow", "€"))
            self.check_in_add_add_button.setText(_translate("MainWindow", "Crear"))
            self.check_in_label1.setText(_translate("MainWindow", "Crear"))
            self.check_in_label2.setText(_translate("MainWindow", "Buscar"))
            self.check_in_search_end_label.setText(_translate("MainWindow", "Hasta"))
            self.check_in_search_search_button.setText(_translate("MainWindow", "Buscar"))
            self.check_in_search_begin_label.setText(_translate("MainWindow", "Desde"))
            item = self.check_in_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "Fecha"))
            item = self.check_in_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "Cuantía"))
            self.check_in_search_total_label.setText(_translate("MainWindow", "Total:"))
            self.section.setTabText(self.section.indexOf(self.check_in), _translate("MainWindow", "Facturación"))
            self.person_add_name_label.setText(_translate("MainWindow", "Nombre"))
            self.person_add_description_label.setText(_translate("MainWindow", "Descripción"))
            self.person_add_add_button.setText(_translate("MainWindow", "Crear"))
            self.person_search_name_label.setText(_translate("MainWindow", "Nombre"))
            self.person_search_number_label.setText(_translate("MainWindow", "ID"))
            item = self.person_search_table.horizontalHeaderItem(0)
            item.setText(_translate("MainWindow", "ID"))
            item = self.person_search_table.horizontalHeaderItem(1)
            item.setText(_translate("MainWindow", "Nombre"))
            item = self.person_search_table.horizontalHeaderItem(2)
            item.setText(_translate("MainWindow", "Deuda total"))
            item = self.person_search_table.horizontalHeaderItem(3)
            item.setText(_translate("MainWindow", "Descripción"))
            self.person_search_table.setColumnWidth(3, 190)
            self.person_search_search_button.setText(_translate("MainWindow", "Buscar"))
            self.person_search_description_label.setText(_translate("MainWindow", "Descripción"))
            self.person_label1.setText(_translate("MainWindow", "Crear personaje"))
            self.person_label2.setText(_translate("MainWindow", "Buscar"))
            self.section.setTabText(self.section.indexOf(self.person), _translate("MainWindow", "Persona"))